import http.server, socketserver, threading
from playwright.sync_api import sync_playwright

root = r"C:/Users/jordi/talentup-fichaje/frontend"
handler = lambda *a, **kw: http.server.SimpleHTTPRequestHandler(*a, directory=root, **kw)
httpd = socketserver.TCPServer(("127.0.0.1", 8771), handler)
t = threading.Thread(target=httpd.serve_forever, daemon=True); t.start()

with sync_playwright() as p:
    b = p.chromium.launch(headless=True)
    page = b.new_context(viewport={"width": 1440, "height": 900}).new_page()
    errs = []
    page.on("pageerror", lambda e: errs.append("PE: " + str(e)))
    page.on("console", lambda m: errs.append("console." + m.type + ": " + m.text) if m.type == "error" else None)
    r = page.goto("http://127.0.0.1:8771/dashboard_new.html", wait_until="networkidle")
    page.wait_for_timeout(2500)
    print("STATUS:", r.status if r else None)
    print("TITLE:", page.title())
    print("view count:", page.locator(".view").count())
    print("nav-item count:", page.locator("#nav-list .nav-item").count())
    print("nav-item data-views:", page.eval_on_selector_all("#nav-list .nav-item", "e=>e.map(x=>x.getAttribute('data-view'))"))
    print("kpi-card count:", page.locator("#kpi-grid .kpi-card").count())
    print("kpi-spark count:", page.locator("#kpi-grid .kpi-spark").count())
    print("dash svg count:", page.locator("#view-dashboard svg").count())
    print("bar chart:", page.locator('svg[aria-label="Fichajes por dia de la ultima semana"]').count())
    print("line chart:", page.locator('svg[aria-label="Evolucion de horas trabajadas en las ultimas 4 semanas"]').count())
    print("dash-donut svg:", page.locator("#dash-donut svg").count())
    print("nav-emp-count text:", page.locator("#nav-emp-count").inner_text())
    print("emp-count-label text:", page.locator("#emp-count-label").inner_text())
    print("dash-today-tbody rows:", page.locator("#dash-today-tbody tr").count())
    print("dash-alerts items:", page.locator("#dash-alerts .alert-item").count())
    print("dash-alert-count:", page.locator("#dash-alert-count").inner_text())
    print("dash-calendar days:", page.locator("#dash-calendar .calendar-day").count())
    print("dash-calendar is-today:", page.locator("#dash-calendar .calendar-day.is-today").count())
    print("progress-fill width:", page.eval_on_selector("#progress-fill", "e=>getComputedStyle(e).width"))
    page.locator('#nav-list .nav-item[data-view="empleados"]').click(timeout=5000)
    page.wait_for_timeout(1000)
    print("after click empleados - active view:", page.locator(".view.is-active").get_attribute("data-view"))
    print("emp-tbody rows:", page.locator("#emp-tbody tr").count())
    print("emp h1:", page.locator(".view.is-active .page-head h1").first.inner_text())
    # reportes
    page.locator('#nav-list .nav-item[data-view="reportes"]').click(timeout=5000)
    page.wait_for_timeout(1200)
    print("reportes svg:", page.locator("#view-reportes svg").count())
    print("area chart:", page.locator('svg[aria-label="Evolucion de horas trabajadas"]').count())
    print("reportes-donut svg:", page.locator("#reportes-donut svg").count())
    print("reportes-rings svg:", page.locator("#reportes-rings svg").count())
    print("heatmap rows:", page.locator("#heatmap .heatmap-row").count())
    print("heatmap cells:", page.locator("#heatmap .heatmap-cell").count())
    print("rank-extra items:", page.locator("#rank-extra .rank-item").count())
    print("rank-tarde items:", page.locator("#rank-tarde .rank-item").count())
    # incidencias
    page.locator('#nav-list .nav-item[data-view="incidencias"]').click(timeout=5000)
    page.wait_for_timeout(1000)
    print("incident-card count:", page.locator("#incident-list .incident-card").count())
    print("data-resolve count:", page.locator("[data-resolve]").count())
    # ajustes
    page.locator('#nav-list .nav-item[data-view="ajustes"]').click(timeout=5000)
    page.wait_for_timeout(800)
    print("tab-panel count:", page.locator(".tab-panel").count())
    print("device-card count:", page.locator("#device-list .device-card").count())
    print("JS ERRORS:", errs[:10])
    b.close()
httpd.shutdown()