apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db:5432
    database: talentup_fichaje
    user: talentup
    secureJsonData:
      password: talentup_secret
    isDefault: true
    editable: true
