[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit PN532 @ ^1.3
    bblanchon/ArduinoJson @ ^6.21.0

; LittleFS viene incluido en el core de ESP32 (framework arduino),
; por lo que no es necesario añadirla como librería externa.

; SPI no requiere librería externa (built-in del core ESP32).
; WiFi y HTTPClient también son built-in.

; Opcional: partición con mayor espacio para LittleFS
; board_build.partitions = default.csv
